### ISSUE TITLE
run example_douyin8.py raise err

### ISSUE THREAD

**Issue by kingking888** [maiyao1988/ExAndroidNativeEmu#14]
2020-03-22 21:38:05,261    INFO         androidemu.vfs.file_system | Reading 1 bytes from '/proc/self/cmdline'
2020-03-22 21:38:05,262    INFO    androidemu.cpu.syscall_handlers | syscall 6 lr=0xCBBE19FD
2020-03-22 21:38:05,262   DEBUG    androidemu.cpu.syscall_handlers | Executing syscall close(0x00000004) at 0xCBBD4EA0
2020-03-22 21:38:05,263    INFO         androidemu.vfs.file_system | File closed '/proc/self/cmdline'
2020-03-22 21:38:05,567    INFO    androidemu.cpu.syscall_handlers | syscall 359 lr=0xCBBE4A81
2020-03-22 21:38:05,568   DEBUG    androidemu.cpu.syscall_handlers | Executing syscall pipe2(0x100FE2D0, 0x00000000) at 0xCBBD4EA0
2020-03-22 21:38:05,568   ERROR    androidemu.cpu.syscall_handlers | An error occured during in 167 syscall hander, stopping emulation
Traceback (most recent call last):
  File "D:\PyhonProject\venv\Projects\fridahook\ExAndroidNativeEmu\androidemu\cpu\syscall_handlers.py", line 43, in _handle_syscall
    result = handler.callback(mu, *args)
  File "D:\PyhonProject\venv\Projects\fridahook\ExAndroidNativeEmu\androidemu\cpu\syscall_hooks.py", line 353, in __pipe2
    raise NotImplementedError()
NotImplementedError
2020-03-22 21:38:05,624   ERROR   androidemu.cpu.interrupt_handler | exception in _hook_interrupt intno:[2]
Traceback (most recent call last):
  File "D:\PyhonProject\venv\Projects\fridahook\ExAndroidNativeEmu\androidemu\cpu\interrupt_handler.py", line 24, in _hook_interrupt
    self._handlers[intno](uc)
  File "D:\PyhonProject\venv\Projects\fridahook\ExAndroidNativeEmu\androidemu\cpu\syscall_handlers.py", line 43, in _handle_syscall
    result = handler.callback(mu, *args)
  File "D:\PyhonProject\venv\Projects\fridahook\ExAndroidNativeEmu\androidemu\cpu\syscall_hooks.py", line 353, in __pipe2
    raise NotImplementedError()
NotImplementedError

**Comment by maiyao1988** [comment]
这个还没好，还在适配

**Comment by maiyao1988** [comment]
最新版本已fix

**Comment by kingking888** [comment]
goodjob  dalao

**Comment by satng** [comment]
goodjob dalao,期待看雪里出一篇详细的动态分析及调试的帖子

**Comment by playniuniu** [comment]
真是太厉害了，大佬能出篇教程，讲一下新版的 exandroidemu 有什么改动，以及 libcms8 是怎么调试的吗？

**Comment by satng** [comment]
测试了下，最新10，可用，建议rebase commits，去掉**yin **dou,被请去喝茶就不好了
