### ISSUE TITLE
virtual_file找不到

### ISSUE THREAD

**Issue by zbx911** [maiyao1988/ExAndroidNativeEmu#18]
File "G:\Unicorn\ExAndroidNativeEmu-master\androidemu\pcb.py", line 8, in <module>
    from androidemu.vfs.virtual_file import VirtualFile
ModuleNotFoundError: No module named 'androidemu.vfs.virtual_file'

**Comment by widy28** [comment]
我也是这个错误提示，看了下代码提交记录，androidemu\pcb.py 看样子是后加的，但是好像from androidemu.vfs.virtual_file这个文件未提交，期待作者文件补上，感谢。

**Comment by widy28** [comment]
手动添加了androidemu/vfs/virtual_file.py文件，
`class VirtualFile:

    def __init__(self, name, file_descriptor, name_in_system=None):
        self.name = name
        self.name_virt = name_in_system
        self.descriptor = file_descriptor
`
运行
`python example_douyin8.py`

报错：
`Traceback (most recent call last):
  File "/Users/ExAndroidNativeEmu/androidemu/cpu/syscall_handlers.py", line 43, in _handle_syscall
    result = handler.callback(mu, *args)
  File "/Users/ExAndroidNativeEmu/androidemu/cpu/syscall_hooks.py", line 409, in _socket
    s = socket.socket(family, type_in, protocol)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 47] Address family not supported by protocol family
62583 - 2020-04-05 15:48:26,268 - ERROR - exception in _hook_interrupt intno:[2]
Traceback (most recent call last):
  File "/Users/ExAndroidNativeEmu/androidemu/cpu/interrupt_handler.py", line 24, in _hook_interrupt
    self._handlers[intno](uc)
  File "/Users/ExAndroidNativeEmu/androidemu/cpu/syscall_handlers.py", line 43, in _handle_syscall
    result = handler.callback(mu, *args)
  File "/Users/ExAndroidNativeEmu/androidemu/cpu/syscall_hooks.py", line 409, in _socket
    s = socket.socket(family, type_in, protocol)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 47] Address family not supported by protocol family`

**Comment by maiyao1988** [comment]
文件已经补上
@widy28 是这样子的，我因为需要要实现大量系统调用，于是将系统调用转给系统了，如果系统不支持这些系统调用那么该系统暂时不支持，目前mac和linux是可以的，windows的话，因为跟android区别比较大，所以暂时不支持。
