### ISSUE TITLE
unicorn.unicorn.UcError: Invalid instruction (UC_ERR_INSN_INVALID)

### ISSUE THREAD

**Issue by widy28** [maiyao1988/ExAndroidNativeEmu#20]
```
7933 - 2020-04-10 01:18:20,813 - ERROR - => Undefined external symbol: 
7933 - 2020-04-10 01:18:20,813 - ERROR - => Undefined external symbol: __cxa_finalize
7933 - 2020-04-10 01:18:20,813 - ERROR - => Undefined external symbol: __cxa_atexit
7933 - 2020-04-10 01:18:20,813 - ERROR - => Undefined external symbol: memcpy
```

```
Traceback (most recent call last):
  File "example_wochacha.py", line 171, in <module>
    result = x.enReq(emulator, arr, size)
  File "/Users/Documents/workspace/programs/frida-work/ExAndroidNativeEmu/androidemu/java/java_method_def.py", line 41, in native_wrapper
    *extra_args  # Extra args.
  File "/Users/Documents/workspace/programs/frida-work/ExAndroidNativeEmu/androidemu/emulator.py", line 181, in call_native
    r = self.mu.emu_start(addr, stop_pos - 1)
  File "/Users/.local/share/virtualenvs/frida-work-l1_vgqRW/lib/python3.7/site-packages/unicorn/unicorn.py", line 317, in emu_start
    raise UcError(status)
unicorn.unicorn.UcError: Invalid instruction (UC_ERR_INSN_INVALID)
```
请教一下这个错误是什么原因？是由于上面的那几个ERROR造成的吗？找了些文章实在不知道哪里的问题。调了好久。来这里请教一下。感谢。

**Comment by maiyao1988** [comment]
这个原因很多，有可能是so本身因缺少调用某些函数而初始化未完成，也有可能某些系统调用而导致他跑了错误的逻辑，需要具体情况具体分析

**Comment by maiyao1988** [comment]
经过分析，原so必走的逻辑interface_c1函数尾段并非指令。
