### ISSUE TITLE
怎么实现signature

### ISSUE THREAD

**Issue by onegithuber** [maiyao1988/ExAndroidNativeEmu#33]
```
Traceback (most recent call last):
  File "/Users/dunchen/PycharmProjects/ExAndroidNativeEmu/androidemu/hooker.py", line 100, in _hook
    hook_func(self._emu)
  File "/Users/dunchen/PycharmProjects/ExAndroidNativeEmu/androidemu/java/helpers/native_method.py", line 112, in native_method_wrapper
    native_write_arg_register(emu, UC_ARM_REG_R0, result)
  File "/Users/dunchen/PycharmProjects/ExAndroidNativeEmu/androidemu/java/helpers/native_method.py", line 83, in native_write_arg_register
    emu.mu.reg_write(reg, native_translate_arg(emu, val))
  File "/Users/dunchen/PycharmProjects/ExAndroidNativeEmu/androidemu/java/helpers/native_method.py", line 79, in native_translate_arg
    raise NotImplementedError("Unable to write response '%s' type '%s' to emulator." % (str(val), type(val)))
NotImplementedError: Unable to write response '[<androidemu.java.classes.package_manager.Signature object at 0x111d4ef60>]' type '<class 'list'>' to emulator.
```
```
class Signature(metaclass=JavaClassDef,jvm_name='android/content/pm/Signature'):
    def __init__(self):
        pass

    @java_method_def(name='hashCode', signature='()I', native=False)
    def hashCode(self):
        pass

class PackageInfo(metaclass=JavaClassDef, jvm_name='android/content/pm/PackageInfo', 
jvm_fields=[
                     JavaFieldDef('applicationInfo', 'Landroid/content/pm/ApplicationInfo;', False),
                     JavaFieldDef('firstInstallTime', 'J', False),
                     JavaFieldDef('lastUpdateTime', 'J', False),
                     JavaFieldDef('signatures','[Landroid/content/pm/Signature;',False)
                    ]):
    def __init__(self, pyPkgName):
        self.applicationInfo = ApplicationInfo(pyPkgName)
        self.firstInstallTime = int(time.time())
        self.lastUpdateTime = self.firstInstallTime
        self.signature = Signature()
        self.signatures = [self.signature]
```

**Comment by onegithuber** [comment]
早期的版本这么写是可以的，最新的版本报错了。

**Comment by maiyao1988** [comment]
给复现的脚本，和so，我查一下。

**Comment by onegithuber** [comment]
[a.zip](https://github.com/maiyao1988/ExAndroidNativeEmu/files/4591600/a.zip)
so和脚本

**Comment by maiyao1988** [comment]
粗看了一下，这个so有签名校验，如果想绕过他检测就把原签名返回给他。

**Comment by onegithuber** [comment]
在hashcode 直接return给他吗

**Comment by maiyao1988** [comment]
如果他调用hash code，那么你先hook原包的hash code，看返回什么，然后这里写死给他就行
