### ISSUE TITLE
get_reference 错误

### ISSUE THREAD

**Issue by onegithuber** [maiyao1988/ExAndroidNativeEmu#37]
```
41414 - 2020-05-25 16:08:26,379 - DEBUG - JNIEnv->GetMethodId(250, deviceId, ()Ljava/lang/String;) was called
Traceback (most recent call last):
  File "/Users/PycharmProjects/ExAndroidNativeEmu/androidemu/hooker.py", line 100, in _hook
    hook_func(self._emu)
  File "/Users/PycharmProjects/ExAndroidNativeEmu/androidemu/java/helpers/native_method.py", line 109, in native_method_wrapper
    result = func(argv[0], mu, *native_args)
  File "/Users/PycharmProjects/ExAndroidNativeEmu/androidemu/java/jni_env.py", line 676, in get_method_id
    raise ValueError('Expected a jclass.')
ValueError: Expected a jclass.
```

**Comment by maiyao1988** [comment]
给一下复现脚本以及so

**Comment by onegithuber** [comment]
发您邮箱了
