### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcb in position 0 

### ISSUE THREAD

**Issue by Rh3x4r** [maiyao1988/ExAndroidNativeEmu#38]
6023 - 2020-06-09 18:07:23,112 - ERROR - An error occured during in 147 syscall hander, stopping emulation
Traceback (most recent call last):
  File "/Users/raju/raju/soft/ExAndroidNativeEmu/androidemu/cpu/syscall_handlers.py", line 43, in _handle_syscall
    result = handler.callback(mu, *args)
  File "/Users/raju/raju/soft/ExAndroidNativeEmu/androidemu/vfs/file_system.py", line 521, in _handle_fstatat64
    pathname = memory_helpers.read_utf8(mu, pathname_ptr)
  File "/Users/raju/raju/soft/ExAndroidNativeEmu/androidemu/utils/memory_helpers.py", line 26, in read_utf8
    return buffer[:null_pos].decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcb in position 0: unexpected end of data
6023 - 2020-06-09 18:07:23,113 - ERROR - exception in _hook_interrupt intno:[2]
Traceback (most recent call last):
  File "/Users/raju/raju/soft/ExAndroidNativeEmu/androidemu/cpu/interrupt_handler.py", line 24, in _hook_interrupt
    self._handlers[intno](uc)
  File "/Users/raju/raju/soft/ExAndroidNativeEmu/androidemu/cpu/syscall_handlers.py", line 43, in _handle_syscall
    result = handler.callback(mu, *args)
  File "/Users/raju/raju/soft/ExAndroidNativeEmu/androidemu/vfs/file_system.py", line 521, in _handle_fstatat64
    pathname = memory_helpers.read_utf8(mu, pathname_ptr)
  File "/Users/raju/raju/soft/ExAndroidNativeEmu/androidemu/utils/memory_helpers.py", line 26, in read_utf8
    return buffer[:null_pos].decode("utf-8")
[UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcb in position 0](url): unexpected end of data

T@kT@k  apk--> https://www21.zippyshare.com/v/rw7SMEGq/file.html

libcms .so --> https://www21.zippyshare.com/v/zNiqBaxx/file.html

**Comment by Rh3x4r** [comment]
thanks in advance ...:-)

**Comment by satng** [comment]
init_proc 里有字符串解密，ida去调，解密过程模拟太麻烦，基本上已经没脾气了，放弃了。

**Comment by maiyao1988** [comment]
看样子是读出来的东西错了，应该是前面的步骤没做好导致的问题，往前查查签名的jni和系统调用

**Comment by Rh3x4r** [comment]
> init_proc 里有字符串解密，ida去调，解密过程模拟太麻烦，基本上已经没脾气了，放弃了。

Is there any way to make it  possible
