### ISSUE TITLE
run  the  example_bb.py ....

### ISSUE THREAD

**Issue by kingking888** [maiyao1988/ExAndroidNativeEmu#41]
`map addr:0xCBD6A000, end:0xCBDBC580, sz:0x00052580 off=0x00000000
read for offset 0 sz 337280 data sz:337280
map addr:0xCBDBD000, end:0xCBDBD000, sz:0x00000000 off=0x00000000
map addr:0xCBDBE000, end:0xCBDC3614, sz:0x00005614 off=0x00053000
read for offset 339968 sz 22036 data sz:22036
map addr:0xCBDC4000, end:0xCBDD8000, sz:0x00014000 off=0x00000000
8472 - 2020-06-14 20:44:56,142 - ERROR - => Undefined external symbol: 
Calling Init_array tests/bin/libSecShell.so function: 0xCBD76FD9 
8472 - 2020-06-14 20:44:56,155 - INFO - syscall 20 lr=0xCBD7705B
8472 - 2020-06-14 20:44:56,155 - DEBUG - Executing syscall getpid() at 0xCBCAD404
8472 - 2020-06-14 20:44:56,161 - INFO - syscall 5 lr=0xCBCBA761
8472 - 2020-06-14 20:44:56,161 - DEBUG - Executing syscall open(0x100FFDDC, 0x00020000, 0x00000000) at 0xCBCAD358
8472 - 2020-06-14 20:44:56,178 - INFO - openat return fd 15
8472 - 2020-06-14 20:44:56,179 - INFO - syscall 197 lr=0xCBCA1CB3
8472 - 2020-06-14 20:44:56,179 - DEBUG - Executing syscall fstat64(0x0000000F, 0x100FF960) at 0xCBCADAC8
8472 - 2020-06-14 20:44:56,180 - ERROR - An error occured during in c5 syscall hander, stopping emulation
Traceback (most recent call last):
  File "D:\PyhonProject\venv\GitHub_Projects\AndroidNativeSimulator\ExAndroidNativeEmu\androidemu\cpu\syscall_handlers.py", line 43, in _handle_syscall
    result = handler.callback(mu, *args)
  File "D:\PyhonProject\venv\GitHub_Projects\AndroidNativeSimulator\ExAndroidNativeEmu\androidemu\vfs\file_system.py", line 414, in _handle_fstat64
    file_helpers.stat_to_memory2(mu, buf_ptr, stats, uid)
  File "D:\PyhonProject\venv\GitHub_Projects\AndroidNativeSimulator\ExAndroidNativeEmu\androidemu\vfs\file_helpers.py", line 46, in stat_to_memory2
    uc.mem_write(buf_ptr + 12, int(stat.st_ino).to_bytes(4, byteorder='little'))
OverflowError: int too big to convert
8472 - 2020-06-14 20:44:56,181 - ERROR - exception in _hook_interrupt intno:[2]
Traceback (most recent call last):
  File "D:\PyhonProject\venv\GitHub_Projects\AndroidNativeSimulator\ExAndroidNativeEmu\androidemu\cpu\interrupt_handler.py", line 24, in _hook_interrupt
    self._handlers[intno](uc)
  File "D:\PyhonProject\venv\GitHub_Projects\AndroidNativeSimulator\ExAndroidNativeEmu\androidemu\cpu\syscall_handlers.py", line 43, in _handle_syscall
    result = handler.callback(mu, *args)
  File "D:\PyhonProject\venv\GitHub_Projects\AndroidNativeSimulator\ExAndroidNativeEmu\androidemu\vfs\file_system.py", line 414, in _handle_fstat64
    file_helpers.stat_to_memory2(mu, buf_ptr, stats, uid)
  File "D:\PyhonProject\venv\GitHub_Projects\AndroidNativeSimulator\ExAndroidNativeEmu\androidemu\vfs\file_helpers.py", line 46, in stat_to_memory2
    uc.mem_write(buf_ptr + 12, int(stat.st_ino).to_bytes(4, byteorder='little'))
OverflowError: int too big to convert`

**Comment by FinchZ** [comment]
same problem

**Comment by FinchZ** [comment]
![QQ截图20200706111507](https://user-images.githubusercontent.com/46061991/86552459-aac25800-bf7a-11ea-942b-113f011b6b24.png)

uc.mem_write(buf_ptr + 12, int(stat.st_ino).to_bytes(4, byteorder='little'))
OverflowError: int too big to convert

**Comment by HCZHONG** [comment]
你好请问下解决了吗
