### ISSUE TITLE
Failed To Load Library

### ISSUE THREAD

**Issue by apkunpacker** [maiyao1988/ExAndroidNativeEmu#42]
$ pip install -r requirements.txt
Requirement already satisfied: unicorn==1.0.1 in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (1.0.1)
Requirement already satisfied: capstone==4.0.1 in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (4.0.1)

$ python example_jni.py
Traceback (most recent call last):                           
File "/data/data/com.termux/files/home/ExAndroidNativeEmu-master/example_jni.py", line 9, in <module>
   from androidemu.emulator import Emulator                
File "/data/data/com.termux/files/home/ExAndroidNativeEmu-master/androidemu/emulator.py", line 19, in <module>          
  from .hooker import Hooker                               
File "/data/data/com.termux/files/home/ExAndroidNativeEmu-master/androidemu/hooker.py", line 1, in <module>           
  from .keystone_in import Ks, KS_ARCH_ARM, KS_MODE_THUMB
File "/data/data/com.termux/files/home/ExAndroidNativeEmu-master/androidemu/keystone_in/__init__.py", line 4, in <module>
    from .keystone import Ks, ks_version, ks_arch_supported, version_bind, debug, KsError, __version__
File "/data/data/com.termux/files/home/ExAndroidNativeEmu-master/androidemu/keystone_in/keystone.py", line 75, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.
$

All Example showing fail to load dynamic library.

**Comment by apkunpacker** [comment]
Fixed the error by updating keystone-engine.
