### ISSUE TITLE
unicorn.unicorn.UcError: Invalid memory write (UC_ERR_WRITE_UNMAPPED)

### ISSUE THREAD

**Issue by onegithuber** [maiyao1988/ExAndroidNativeEmu#5]
Traceback (most recent call last):
  File "/Users/PycharmProjects/ExAndroidNativeEmu/example_grab.py", line 176, in <module>
    emulator.load_library("tests/bin/libc.so", do_init=False)
  File "/Users/PycharmProjects/ExAndroidNativeEmu/androidemu/emulator.py", line 144, in load_library
    libmod = self.modules.load_module(filename, True)
  File "/Users/PycharmProjects/ExAndroidNativeEmu/androidemu/internal/modules.py", line 345, in load_module
    module.call_init(self.emu)
  File "/Users/PycharmProjects/ExAndroidNativeEmu/androidemu/internal/module.py", line 42, in call_init
    emu.call_native(fun_ptr)
  File "/Users/PycharmProjects/ExAndroidNativeEmu/androidemu/emulator.py", line 171, in call_native
    r = self.mu.emu_start(addr, stop_pos - 1)
  File "/Users/.conda/envs/wecash/lib/python3.6/site-packages/unicorn-1.0.2-py3.6.egg/unicorn/unicorn.py", line 317, in emu_start
unicorn.unicorn.UcError: Invalid memory write (UC_ERR_WRITE_UNMAPPED)

**Comment by maiyao1988** [comment]
can you provide script and so?

**Comment by Dddddz** [comment]
i'm using command "pip3.7 install --trusted-host pypi.org --trusted-host files.pythonhosted.org -r requirements.txt",but it report error:
 running install
    running build
    Building C extensions
    cd qemu && \
    	./configure --cc="cc" --extra-cflags="-DUNICORN_HAS_X86 -DUNICORN_HAS_ARM -DUNICORN_HAS_ARMEB -DUNICORN_HAS_M68K -DUNICORN_HAS_ARM64 -DUNICORN_HAS_MIPS -DUNICORN_HAS_MIPSEL -DUNICORN_HAS_MIPS64 -DUNICORN_HAS_MIPS64EL -DUNICORN_HAS_SPARC -fPIC -fvisibility=hidden -m32 -arch i386 -m64 -arch x86_64" --target-list="x86_64-softmmu, arm-softmmu, armeb-softmmu, m68k-softmmu, aarch64-softmmu, mips-softmmu, mipsel-softmmu, mips64-softmmu, mips64el-softmmu, sparc-softmmu,sparc64-softmmu,"
    
    ERROR: Cannot use 'python', Python 2.4 or later is required.
           Note that Python 3 or later is not yet supported.
           Use --python=/path/to/python to specify a supported Python.
    
    make: *** [qemu/config-host.h-timestamp] Error 1
    error: [Errno 2] No such file or directory: 'libunicorn.dylib'

how can i fix it?

**Comment by onegithuber** [comment]
libc.so has been loaded twice。
