### ISSUE TITLE
callback catch the exception but can't exit

### ISSUE THREAD

**Issue by LLeavesG** [maiyao1988/ExAndroidNativeEmu#54]
Thanks for your good work, i found that the exception wound be caught when the hook_func error in hooker.py .However the emulator restart and repeat the error always but can not exit. 

```python
        # Call hook.
        try:
            hook_func(self._emu)
        except Exception as e:
            # Make sure we catch exceptions inside hooks and stop emulation.
            mu.emu_stop()
            traceback.print_exc()
            logging.exception("catch error on _hook")
            sys.exit(-1)
```

```python
2022-02-08 22:25:38,500   DEBUG            androidemu.java.jni_env | JNIEnv->GetObjectClass(<androidemu.java.classes.package_manager.PackageInfo object at 0x0000017FFF996460>) was called
2022-02-08 22:25:38,859   DEBUG            androidemu.java.jni_env | JNIEnv->GetFieldId(9, signatures, [Landroid/content/pm/Signature;) was called
2022-02-08 22:25:39,267   DEBUG            androidemu.java.jni_env | JNIEnv->GetXXXField(android/content/pm/PackageInfo, signatures <[Landroid/content/pm/Signature;>) was called
Traceback (most recent call last):
  File "e:\pythoncode\ExAndroidEmu\androidemu\hooker.py", line 106, in _hook
    hook_func(self._emu)
  File "e:\pythoncode\ExAndroidEmu\androidemu\java\helpers\native_method.py", line 123, in native_method_wrapper
    result = func(argv[0], mu, *native_args)
  File "e:\pythoncode\ExAndroidEmu\androidemu\java\jni_env.py", line 1238, in get_object_field
    return self.__get_xxx_field(mu, env, obj_idx, field_id)
  File "e:\pythoncode\ExAndroidEmu\androidemu\java\jni_env.py", line 1227, in __get_xxx_field
    v = getattr(pyobj, field.name)
AttributeError: 'PackageInfo' object has no attribute 'signatures'
2022-02-08 22:25:39,867   ERROR                               root | catch error on _hook
Traceback (most recent call last):
  File "e:\pythoncode\ExAndroidEmu\androidemu\hooker.py", line 106, in _hook
    hook_func(self._emu)
  File "e:\pythoncode\ExAndroidEmu\androidemu\java\helpers\native_method.py", line 123, in native_method_wrapper
    result = func(argv[0], mu, *native_args)
  File "e:\pythoncode\ExAndroidEmu\androidemu\java\jni_env.py", line 1238, in get_object_field
    return self.__get_xxx_field(mu, env, obj_idx, field_id)
  File "e:\pythoncode\ExAndroidEmu\androidemu\java\jni_env.py", line 1227, in __get_xxx_field
    v = getattr(pyobj, field.name)
AttributeError: 'PackageInfo' object has no attribute 'signatures'
Exception ignored on calling ctypes callback function: <bound method Uc._hookcode_cb of <unicorn.unicorn.Uc object at 0x0000017FFE042F40>>
Traceback (most recent call last):
  File "E:\Anaconda3\lib\site-packages\unicorn\unicorn.py", line 438, in _hookcode_cb
    cb(self, address, size, data)
  File "e:\pythoncode\ExAndroidEmu\androidemu\hooker.py", line 112, in _hook
    sys.exit(-1)
SystemExit: -1
2022-02-08 22:25:39,872   DEBUG                               root | 21020 scheduling paused
2022-02-08 22:25:39,872   DEBUG                               root | 21020 scheduling enter
2022-02-08 22:25:41,135   DEBUG            androidemu.java.jni_env | JNIEnv->GetXXXField(android/content/pm/PackageInfo, signatures <[Landroid/content/pm/Signature;>) was called
Traceback (most recent call last):
  File "e:\pythoncode\ExAndroidEmu\androidemu\hooker.py", line 106, in _hook
    hook_func(self._emu)
  File "e:\pythoncode\ExAndroidEmu\androidemu\java\helpers\native_method.py", line 123, in native_method_wrapper
    result = func(argv[0], mu, *native_args)
  File "e:\pythoncode\ExAndroidEmu\androidemu\java\jni_env.py", line 1238, in get_object_field
    return self.__get_xxx_field(mu, env, obj_idx, field_id)
  File "e:\pythoncode\ExAndroidEmu\androidemu\java\jni_env.py", line 1227, in __get_xxx_field
    v = getattr(pyobj, field.name)
AttributeError: 'PackageInfo' object has no attribute 'signatures'
```
just like this , the program trapped in a dead end just because i didn't populate the sign_hex field of the config file.Some error like this   made me trapped in a dead end ， such as `getPackageInfo with PackageManager.GET_SIGNATURES is called but no 'sign_hex' set in config!!!` when i didn't set the sign_hex field also made the error report repeat again and again. Maybe the problem is task schedule section in the scheduler.py.

```json
{
	"__pkg_name":"com.netease.cloudmusic",
	"pkg_name":"com.ss.android.ugc.aweme",
	"pid": 4386,
	"uid": 10023,
	"android_id": "39cc04a2ae83db0b",
	"ip":"192.168.31.52",
	"mac":[204, 250, 166, 0, 138, 169],
	"sign_hex":""
}
```

Thanks again.

**Comment by maiyao1988** [comment]
werid behavior on your enviroment,the process should exit alter sys.exit, is that so call fork???

**Comment by LLeavesG** [comment]
Actually I'm not call `fork` in .so file，and i found there is only one task (main) in schedule.However, when the callback caught the exception and sys.exit , then program return to self.__emu.mu.emu_start(start_pos, self.__stop_pos, 0, 0) and continue to run and i  noticed that when goto `if (self.__get_pc() == self.__stop_pos or task.is_exit):` the task.is_exit is `False` （init is False and never be changed maybe）, which woud not let task tid add to self.__tid_2_remove so that the task will not exit.

**Comment by maiyao1988** [comment]
somebody catch the SystemExit exception and ignore, actually I just want to exit the process when the exception was catch by calling sys.exit.

**Comment by LLeavesG** [comment]
Thanks for your reply again. Yes，i think you are right， maybe somebody catch the SystemExit exception.Howerver i can't find it so i use os.exit . Thanks again ! This project is a great and amazing work based on AndroidNativeEmu ！
