### ISSUE TITLE
jbyteArray类型应该如何定义

### ISSUE THREAD

**Issue by YsielX** [maiyao1988/ExAndroidNativeEmu#64]
原项目是直接有jbyteArray类型的，这里好像将其删除了，请问应该如何定义呢？
```python
# Create java class.
class MainActivity(metaclass=JavaClassDef, jvm_name='com/crackme/bbbbutton/MainActivity'):

    def __init__(self):
        pass

    @java_method_def(name='getBytes', signature='([B)[B', args_list=['jbyteArray'])
    def getBytes(self, *args, **kwargs):
        bArr = args[0].value
        print(bArr, type(bArr))
        bArr2 = bytearray(b'\0'*(len(bArr)//4))
        i = 0
        for i2 in range(len(bArr)//4):
            i3 = i2 * 4
            bArr2[i] = ((bArr[i3] << 6) + (bArr[i3 + 1] << 4) +
                        (bArr[i3 + 2] << 2) + bArr[i3 + 3]) & 0xff
            i += 1
        return bArr2

    def test(self):
        pass
```
报错
```
Traceback (most recent call last):
  File "E:\REVERSE\AndroidNativeEmu\androidemu\hooker.py", line 106, in _hook
    hook_func(self._emu)
  File "E:\REVERSE\AndroidNativeEmu\androidemu\java\helpers\native_method.py", line 123, in native_method_wrapper
    result = func(argv[0], mu, *native_args)
  File "E:\REVERSE\AndroidNativeEmu\androidemu\java\jni_env.py", line 1462, in call_static_object_method_v
    return self.__call_static_xxx_method(mu, env, clazz_idx, method_id, args, 1)
  File "E:\REVERSE\AndroidNativeEmu\androidemu\java\jni_env.py", line 1444, in __call_static_xxx_method
    v = method.func(self._emu, *constructor_args)
  File "E:\REVERSE\AndroidNativeEmu\androidemu\java\java_method_def.py", line 105, in normal_wrapper
    result = func(*args, **kwargs)
  File "E:\REVERSE\AndroidNativeEmu\emu.py", line 71, in getBytes
    bArr = args[0].value
AttributeError: 'bytearray' object has no attribute 'value'
```

**Comment by maiyao1988** [comment]
项目array.py有ByteArray的定义

**Comment by YsielX** [comment]
那我方法定义的args_list参数应该如何填写呢

**Comment by YsielX** [comment]
解决了，填写jobject即可，作者你的jni_env.py get_byte_array_region实现是否有点问题
```python
barr = pyobj.get_py_items()
```
这句话好像会报错，我注释后就可以运行了

**Comment by maiyao1988** [comment]
你传的参数不是Array的子类是有问题的，因为没有实现get_py_items

**Comment by YsielX** [comment]
好的
