### ISSUE TITLE
Emulator initialized with ARCH_ARM64 fails to load SOs

### ISSUE THREAD

**Issue by nk521** [maiyao1988/ExAndroidNativeEmu#76]
Initialized the Emulator like this - 
```python3
emulator = Emulator(
    vfs_root=posixpath.join(posixpath.dirname(__file__), "..", "vfs"),
    vfp_inst_set=True,
    arch=androidemu.const.emu_const.ARCH_ARM64,
    config_path=posixpath.join(posixpath.dirname(__file__), "..", "_emu.cfg")
)

lib_module = emulator.load_library("../extracted_libs/libsome.so")
```

Getting this error - 
```
Traceback (most recent call last):
  File "/some/path/ExAndroidNativeEmu/proxy.py", line 91, in <module>
    lib_module = emulator.load_library("../extracted_libs/libsome.so")
  File "/some/path/ExAndroidNativeEmu/androidemu/emulator.py", line 248, in load_library
    libmod = self.modules.load_module(filename, True)
  File "/some/path/ExAndroidNativeEmu/androidemu/internal/modules.py", line 342, in load_module
    libmod = self.load_module(path)
  File "/some/path/ExAndroidNativeEmu/androidemu/internal/modules.py", line 342, in load_module
    libmod = self.load_module(path)
  File "/some/path/ExAndroidNativeEmu/androidemu/internal/modules.py", line 342, in load_module
    libmod = self.load_module(path)
  [Previous line repeated 1 more time]
  File "/some/path/ExAndroidNativeEmu/androidemu/internal/modules.py", line 334, in load_module
    so_needed = reader.get_so_need()
  File "/some/path/ExAndroidNativeEmu/androidemu/internal/elf_reader.py", line 513, in get_so_need
    return self.__so_needed

AttributeError: 'ELFReader' object has no attribute '_ELFReader__so_needed'. Did you mean: '_ELFReader__dyn_addr'?
```

LDD of the library - 
```
        linux-vdso.so.1 => [vdso] (0x76d06bf000)
        liblog.so => /system/lib64/liblog.so (0x76cf2d0000)
        libc.so => /apex/com.android.runtime/lib64/bionic/libc.so (0x76cc00f000)
        libm.so => /apex/com.android.runtime/lib64/bionic/libm.so (0x76cf301000)
        libdl.so => /apex/com.android.runtime/lib64/bionic/libdl.so (0x76cf29c000)
        libc++.so => /system/lib64/libc++.so (0x76cbf53000)
```

I've all the libs needed in `vfs/system/lib64` but it still fails. I did some digging and found that while fetching all the required library dependencies, it fails when `__so_needed` is never initialized when the library has no dependency. In this case, the dependency chart is somewhat like `libsome.so` -> `liblog.so` -> `libc++.so` -> `libc.so` -> `ld-android.so`, at the stage of parsing `ld-android.so` this error occurs.

**Comment by maryjeck** [comment]
俺也一样
